apiVersion: app/v1
kind: service
metadata:
  name: frontend-service
  namespace: default
  lables:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protcol: TCP
      port: 5137
      targetPort: 5137
  type: ClusterIP
    