apiVersion: app/v1
kind: service
metadata:
  name: backend-service
  namespace: default
  lables:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protcol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
    