
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysqldb-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"        # not using legacy AAD Pod Identity
    useVMManagedIdentity: "false"  # not using node/cluster identity
    clientID: "1d20f7f1-6e02-4da7-b147-893b774b26da"   # UAMI client ID
    keyvaultName: "COE-AKS-KV"
    tenantId: "d01bddfc-dfec-4fe0-b513-d03d4fe53f40"
    objects: |
      array:
        - |
          objectName: MYSQL-ROOT-PASSWORD
          objectType: secret
          objectVersion: ""        # latest
        - | 
          objectName: MYSQL-DATABASE
          objectType: secret
          objectVersion: ""        # latest
        - |
          objectName: MYSQL-USER
          objectType: secret
          objectVersion: ""        # latest
        - |
          objectName: MYSQL-PASSWORD
          objectType: secret
          objectVersion: ""        # latest
  secretObjects:    
    - secretName: mysqldb-secret
      type: Opaque
      data:
        - objectName: MYSQL-ROOT-PASSWORD
          key: MYSQL_ROOT_PASSWORD
        - objectName: MYSQL-DATABASE
          key: MYSQL_DATABASE
        - objectName: MYSQL-USER
          key: MYSQL_USER
        - objectName: MYSQL-PASSWORD
          key: MYSQL_PASSWORD

