
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "mydatabase"              # optional: auto-create database
  MYSQL_USER: "myuser"                # optional: create user
  MYSQL_PASSWORD: "mypassword"  # optional: user password


