apiVersion: app/v1
kind: service
metadata:
  name: mysqldb-service
  namespace: default
  lables:
    app: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protcol: TCP
      port: 
      targetPort: 3306
  type: ClusterIP
    